ALTER TABLE family_books ADD COLUMN IF NOT EXISTS bon_gwan VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE family_books ADD COLUMN IF NOT EXISTS branch_name VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE family_books ADD COLUMN IF NOT EXISTS volume VARCHAR(50) NOT NULL DEFAULT '';
