const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let book = null, view = 'people';
function message(text) { $('#message').textContent = text; }
async function api(path, method='GET', data) {
  const options = {method, credentials:'same-origin'};
  if (data instanceof FormData) options.body=data;
  else if (data !== undefined) {options.body=JSON.stringify(data);options.headers={'Content-Type':'application/json'};}
  const r=await fetch('/api'+path,options), result=await r.json();
  if(!r.ok) throw Error(typeof result.detail==='string'?result.detail:'입력값을 확인해 주세요. 날짜와 필수 항목이 올바른지 확인하세요.');
  return result;
}
function run(fn){return async e=>{try{message('');await fn(e);}catch(err){message(err.message);}};}
function formData(form){return Object.fromEntries(new FormData(form));}
async function enter(){await api('/me');$('#auth').hidden=true;$('#workspace').hidden=false;$('#logout').hidden=false;await loadBooks();}
async function loadBooks(selected){const all=await api('/books');$('#bookSelect').innerHTML=all.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join('');if(selected)$('#bookSelect').value=selected;await refresh();}
async function refresh(){const bid=$('#bookSelect').value;book=bid?await api('/books/'+bid):null;$('#bookTitle').textContent=book?.title||'새 족보를 만들어 주세요';$('#relationsPanel').hidden=!book;$('#print').disabled=!book;$('#newPerson').disabled=!book;render();renderRelations();}
$('#authForm').onsubmit=run(async e=>{e.preventDefault();await api('/login','POST',formData(e.target));await enter();});
$('#register').onclick=run(async()=>{if(!$('#authForm').reportValidity())return;const r=await api('/register','POST',formData($('#authForm')));message(r.message);});
$('#logout').onclick=run(async()=>{await api('/logout','POST');location.reload();});
$('#bookForm').onsubmit=run(async e=>{e.preventDefault();const r=await api('/books','POST',formData(e.target));e.target.reset();await loadBooks(r.id);});
$('#bookSelect').onchange=run(refresh);
$('#search').oninput=render;
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});
function personName(id){return book.persons.find(p=>p.id===id)?.korean_name||'';}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(!book){$('#view').innerHTML='<p class="empty">왼쪽에서 족보를 만들거나 가상 가족 예제를 추가해 보세요.</p>';return;}
 const q=$('#search').value.toLowerCase().trim();const people=book.persons.filter(p=>[p.korean_name,p.hanja_name,p.note].join(' ').toLowerCase().includes(q));
 if(view==='tree'){renderTree(people);return;}
 if(view==='book'){$('#view').innerHTML=bookHTML(people);return;}
 $('#view').innerHTML=people.length?'<div class="cards">'+people.map(p=>`<button class="person-card" data-person="${p.id}"><span class="badge">${p.generation}세 · ${esc(p.gender)}</span><strong>${esc(p.korean_name)}</strong><span>${esc(p.hanja_name||'한자명 미등록')}</span><small>${esc(p.birth_date||'출생일 미상')} ${p.death_date?'— '+esc(p.death_date):''}</small></button>`).join('')+'</div>':'<p class="empty">등록된 인물 또는 검색 결과가 없습니다.</p>';
 document.querySelectorAll('[data-person]').forEach(b=>b.onclick=()=>editPerson(Number(b.dataset.person)));
}
function bookHTML(people){const generations=[...new Set(people.map(p=>p.generation))];return `<article class="book-page"><h2>${esc(book.clan_name||book.title)} 世譜</h2><p style="text-align:center">${esc(book.title)} · 가족 기록</p>`+generations.map(g=>`<h3 class="generation-title">第 ${g} 世 · ${g}세</h3>`+people.filter(p=>p.generation===g).map(p=>{const parents=book.relations.filter(r=>r.kind==='parent'&&r.target_id===p.id).map(r=>personName(r.source_id));const spouses=book.relations.filter(r=>r.kind==='spouse'&&(r.target_id===p.id||r.source_id===p.id)).map(r=>personName(r.source_id===p.id?r.target_id:r.source_id));return `<section class="book-person"><div class="vertical">${esc(p.hanja_name||p.korean_name)}</div><div class="bio"><p><b>${esc(p.korean_name)}</b> · ${esc(p.gender)}</p><p>生 ${esc(p.birth_date||'미상')} / 卒 ${esc(p.death_date||'미기록')}</p><p>부모: ${esc(parents.join(', ')||'미기록')} · 배우자: ${esc(spouses.join(', ')||'미기록')}</p><small>${esc(p.note)}</small></div></section>`;}).join('')).join('')+'</article>';}
function renderTree(people){if(!people.length){$('#view').innerHTML='<p class="empty">표시할 인물이 없습니다.</p>';return;}const levels=[...new Set(people.map(p=>p.generation))].sort((a,b)=>a-b), pos=new Map();let width=700;levels.forEach((g,li)=>{const row=people.filter(p=>p.generation===g);width=Math.max(width,row.length*190+80);row.forEach((p,i)=>pos.set(p.id,{x:70+i*190,y:50+li*160}));});
 const edges=book.relations.filter(r=>pos.has(r.source_id)&&pos.has(r.target_id)).map(r=>{const a=pos.get(r.source_id),b=pos.get(r.target_id);return r.kind==='parent'?`<path d="M ${a.x+75} ${a.y+70} C ${a.x+75} ${a.y+115},${b.x+75} ${b.y-45},${b.x+75} ${b.y}" fill="none" stroke="#658a74" stroke-width="2" marker-end="url(#arrow)"/>`:`<path d="M ${a.x+75} ${a.y} Q ${(a.x+b.x)/2+75} ${Math.min(a.y,b.y)-45},${b.x+75} ${b.y}" fill="none" stroke="#ba9153" stroke-width="2" stroke-dasharray="6 4"/>`;}).join('');
 $('#view').innerHTML=`<p class="muted">실선 화살표: 부모 → 자녀 · 금색 점선: 배우자 · 입력된 세대 순서로 표시됩니다.</p><div class="tree-scroll"><svg role="img" aria-label="${esc(book.title)} 가계도" width="${width}" height="${levels.length*160+40}"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="3" orient="auto"><path d="M0,0 L0,6 L8,3 z" fill="#658a74"/></marker></defs>${edges}${people.map(p=>{const a=pos.get(p.id);return `<g><rect x="${a.x}" y="${a.y}" width="150" height="70" rx="8" fill="#f4f6ef" stroke="#cad5c7"/><text x="${a.x+75}" y="${a.y+28}" text-anchor="middle" fill="#23392f" font-size="17">${esc(p.korean_name)}</text><text x="${a.x+75}" y="${a.y+52}" text-anchor="middle" fill="#727a72" font-size="12">${p.generation}세 · ${esc(p.hanja_name)}</text></g>`;}).join('')}</svg></div>`;
}
function editPerson(id){const f=$('#personForm');f.reset();f.elements.id.value=id||'';const p=book.persons.find(p=>p.id===id);if(p)Object.entries(p).forEach(([k,v])=>{if(f.elements.namedItem(k))f.elements.namedItem(k).value=v;});$('#personHeading').textContent=p?'인물 수정':'인물 등록';$('#deletePerson').hidden=!p;$('#attachments').hidden=!p;$('#fileInput').value='';$('#fileList').innerHTML=p?book.files.filter(x=>x.person_id===id).map(x=>`<p><a href="/api/files/${x.id}">${esc(x.name)}</a></p>`).join(''):'';$('#personDialog').showModal();}
$('#newPerson').onclick=()=>editPerson();$('#cancelPerson').onclick=()=>$('#personDialog').close();
$('#personForm').onsubmit=run(async e=>{e.preventDefault();const data=formData(e.target),id=data.id;delete data.id;data.generation=Number(data.generation);await api(id?'/persons/'+id:'/books/'+book.id+'/persons',id?'PUT':'POST',data);$('#personDialog').close();await refresh();message('인물을 저장했습니다.');});
$('#deletePerson').onclick=run(async()=>{if(!confirm('인물과 연결된 관계, 첨부파일을 삭제할까요?'))return;await api('/persons/'+$('#personForm').elements.id.value,'DELETE');$('#personDialog').close();await refresh();});
$('#upload').onclick=run(async()=>{const file=$('#fileInput').files[0];if(!file)throw Error('파일을 선택하세요.');if(file.size>5*1024*1024)throw Error('파일은 5MB 이하만 가능합니다.');const id=Number($('#personForm').elements.id.value),data=new FormData();data.append('file',file);await api('/persons/'+id+'/files','POST',data);await refresh();$('#fileList').innerHTML=book.files.filter(x=>x.person_id===id).map(x=>`<p><a href="/api/files/${x.id}">${esc(x.name)}</a></p>`).join('');$('#fileInput').value='';message('첨부파일을 저장했습니다.');});
function renderRelations(){if(!book)return;const options=book.persons.map(p=>`<option value="${p.id}">${esc(p.korean_name)} (${p.generation}세)</option>`).join('');['source_id','target_id'].forEach(n=>$('#relationForm').elements[n].innerHTML=options);$('#relationList').innerHTML=book.relations.map(r=>`<div class="relation-row"><span>${esc(personName(r.source_id))} ${r.kind==='parent'?'→ 자녀':'↔ 배우자'} ${esc(personName(r.target_id))}</span><button class="secondary" data-relation="${r.id}">관계 삭제</button></div>`).join('');document.querySelectorAll('[data-relation]').forEach(b=>b.onclick=run(async()=>{if(!confirm('이 관계를 삭제할까요?'))return;await api('/relations/'+b.dataset.relation,'DELETE');await refresh();}));}
$('#relationForm').onsubmit=run(async e=>{e.preventDefault();const d=formData(e.target);d.source_id=Number(d.source_id);d.target_id=Number(d.target_id);await api('/relations','POST',d);await refresh();});
$('#print').onclick=()=>{view='book';$('#search').value='';render();window.print();};
$('#sample').onclick=run(async()=>{const button=$('#sample');button.disabled=true;try{const b=await api('/books','POST',{title:'가상 가족의 기록 (샘플)',clan_name:'예시 김씨',description:'실존 인물과 무관한 예제입니다.'});const people=[{korean_name:'김예시',hanja_name:'金例示',generation:1,birth_date:'1940-01-01',gender:'남'},{korean_name:'이샘플',hanja_name:'李樣本',generation:1,birth_date:'1942-02-02',gender:'여'},{korean_name:'김가상',hanja_name:'金假想',generation:2,birth_date:'1970-03-03',gender:'남'},{korean_name:'김미래',hanja_name:'金未來',generation:3,birth_date:'2000-04-04',gender:'미상'}];const ids=[];for(const p of people)ids.push((await api('/books/'+b.id+'/persons','POST',{...p,note:'실제 개인정보가 아닌 가상 인물입니다.'})).id);for(const [s,t,kind] of [[0,1,'spouse'],[0,2,'parent'],[1,2,'parent'],[2,3,'parent']])await api('/relations','POST',{source_id:ids[s],target_id:ids[t],kind});await loadBooks(b.id);message('가상 가족 예제를 추가했습니다.');}finally{button.disabled=false;}});
enter().catch(()=>{});
